### PR TITLE
[imp]: Add ability for users to edit their avatar

### PR DESCRIPTION
**Pull request by ordersys**

### CODE REVIEW

**Comment by ordersys** [comment]
will you leave comment on upwork? and pay via upwork?

>Пятница,  3 февраля 2017, 11:10 +03:00 от Sean Auriti <notifications@github.com>:
>
>@seanauriti requested changes on this pull request.
>Can you please code this on Bugheist instead?  The avatars are working ok on Coderbounty.
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


----------------------------
end message

**Comment by seanauriti** [comment]
Yes

**Comment by ordersys** [comment]
accept my proposal on upwork, and i will start



>Пятница,  3 февраля 2017, 11:38 +03:00 от Sean Auriti <notifications@github.com>:
>
>Yes
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


----------------------------
end message

**Comment by seanauriti** [comment]
Done

**Comment by ordersys** [comment]
I not see... may be you accepted not me? this is my profile  https://www.upwork.com/o/profiles/users/_~015179ea6c5096187e/   


>Пятница,  3 февраля 2017, 11:53 +03:00 от Sean Auriti <notifications@github.com>:
>
>Done
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


----------------------------
end message

**Comment by seanauriti** [comment]
fixed

**Pull request closed without merging**
